#pragma once
#include <ntddk.h>

NTSTATUS driver_irp_dispatch(PDEVICE_OBJECT DeviceObject, PIRP Irp);


#define IOCTL_SET_BLACK_MEMORY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x900, METHOD_IN_DIRECT, FILE_ANY_ACCESS)


#define IOCTL_GET_LAST_THREAD_ID \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x901, METHOD_IN_DIRECT, FILE_ANY_ACCESS)